### ISSUE TITLE
Auto layout update

### ISSUE THREAD

**Issue by ggschelling** [dehli/TouchDraw#28] opened 2017-12-15 13:19 UTC
When I trigger an orientation change, the TouchDrawView acts weird. When rotating back to the original orientation, everything works as expected again. I haven't found a way to adjust to a new view size. Maybe I'm just missing something. If not, it would be great to have a function which allows to resize dynamically. Thx!

**Comment by dehli** [comment] 2017-12-15 14:19
Hey @ggschelling, thanks for finding the issue! I will try to reproduce it this weekend and see if I can come up with a solution! Happy holidays!

**Comment by ggschelling** [comment] 2017-12-21 20:06
No problem! Happy holidays! ;)

**Comment by dehli** [comment] 2018-01-08 13:32
To update the issue: I was able to reproduce this but I haven't been able to fix it due to limited time. If you (or anyone else) comes up with a solution in the mean time feel free to submit a PR. Will update this issue as any progress is made. :)

**Comment by ggschelling** [comment] 2018-01-22 15:45
Hey @dehli Sorry, I didn't have the time to check this issue either, and I'm still a newbie with Swift/iOS-dev. But if I manage to take a look and find a solution, you'll get a PR :)

**Comment by dehli** [comment] 2018-05-16 13:36
This was fixed thanks to @mkoorn 🎉  I will close this issue once I release a new version.

**Comment by dehli** [comment] 2018-06-16 13:40
Hi, I finally pushed up a new release on CocoaPods (2.1.2). I'm going to go ahead and close this issue. Feel free to reopen it if you see more issues. Thanks! 😄

**Closed by dehli** 2018-06-16 13:40 UTC
Labels: bug

**Comment by mkoorn** [comment] 2018-08-01 08:09
@dehli I updated my pod file to the latest release. The issue I had with the previous one is back.
If I start drawing and continue to draw the lines will get distorted.
