### ISSUE TITLE
On tap, touchDrawView renders a trail of dots

### ISSUE THREAD

**Issue by tsanjoto** [dehli/TouchDraw#16] opened 2016-09-21 19:06 UTC
Hi! I have an issue on putting a TouchDrawView on top of google mapview, with all the constraints have the same height, width, centered x and y

On a long press or a single stroke it will show a trail of dots instead of an actual stroke
![img_0047](https://cloud.githubusercontent.com/assets/844206/18725031/85e03162-7ff3-11e6-939b-e3de3d2b18f6.PNG)

I also notice that if I put my finger closer to the top left (origin of the TouchDrawView) the dots condensed and thickened into an actual line as seen by the picture. Anyone in TouchDraw can help me on this?

**Comment by tsanjoto** [comment] 2016-09-21 19:15
I've tested that if I attach the TouchDrawView's contraint to the view of the ViewController, it behaves perfectly. but that defeats the purpose on having only a subsection is drawable

**Comment by dehli** [comment] 2016-09-21 19:58
Thanks for pointing this out. What version of `TouchDraw` are you using? I'll try to reproduce the issue and see if I can fix it.

**Comment by tsanjoto** [comment] 2016-09-21 20:21
Using TouchDraw (1.3.1)

**Comment by tsanjoto** [comment] 2016-09-21 20:33
I'll add the UI Debug View Heirarchy for both case

**Comment by tsanjoto** [comment] 2016-09-21 20:34
<img width="1512" alt="screen shot 2016-09-21 at 1 27 53 pm" src="https://cloud.githubusercontent.com/assets/844206/18727978/1452aebe-8000-11e6-9527-0e7b82a7951f.png">

![img_0048](https://cloud.githubusercontent.com/assets/844206/18727968/0ed6c222-8000-11e6-96fe-33de533638fd.PNG)
<img width="1512" alt="screen shot 2016-09-21 at 1 31 29 pm" src="https://cloud.githubusercontent.com/assets/844206/18727977/145218c8-8000-11e6-89fe-ab9c9de6b4db.png">

**Comment by tsanjoto** [comment] 2016-09-21 20:59
As a workaround I'm fine with putting the TouchDrawView on the middle of the uiviews stack, but the drawView still extends beneath the left toolbars. User can draw beneath it, which is somewhat tolerable. 

you can close this issue or keep it open if you want to solve this minor issue.

**Comment by dehli** [comment] 2016-09-21 22:08
Thanks for all of the details! That will help for sure. I'll try to see what I can come up with. I'll keep you updated :)

**Comment by daviddelmonte** [comment] 2016-10-31 13:47
Hi, great control. I have also experienced tsanjoto's issue. I found by aligning my views, I can bypass the issue.

One new feature I'd like to suggest is an eraser function. This could perhaps use CGBlendMode.clear to remove the "paint".

Thanks again

**Comment by dehli** [comment] 2017-06-26 21:31
I'm really sorry for not looking into this more. I'm trying to clean up this library and with that I want to address all of the issues. Were you programmatically adding the `TouchDrawView` or were you still adding it via the Storyboard. In the demo app, the `TouchDrawView` doesn't match its parent's height and it's working fine. Just trying to figure out how to reproduce this.

Thanks!

**Comment by tsanjoto** [comment] 2017-06-27 01:38
This is a pretty long time ago, but as far as I remembered, I added a UIView onto the storyboard and then change the class name to TouchDrawView. My previous project was using the ipad if that makes a difference.

**Comment by dehli** [comment] 2017-06-27 13:34
Thanks for the update! I've tried reproducing this, but I cannot. Maybe the issue has been fixed since you first discovered it? 

I'm going to go ahead and close this issue, but if you (or anyone else) see it again feel free to reopen it!

**Closed by dehli** 2017-06-27 13:34 UTC
Labels: bug
